language: php
sudo: false
php:
    - 7.0
    - 7.1
services:
    - mysql
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - mysql -e 'CREATE TABLE IF NOT EXISTS test;'
  - travis_retry composer self-update
install:
  - travis_retry composer update --no-interaction --prefer-source
script:
  - composer test